### ISSUE TITLE
Changed API END POINT

### ISSUE THREAD

**Issue by VPATEL007** [thingsboard/dart_thingsboard_client#24]
Once Thingboard is initialization after that how can we reinitilization or changes the API end point

**Comment by ybeshkarov** [comment]
Hello @VPATEL007,

Currently, we can't behave like you're asking for. Only by modifying the following field:

```
abstract class ThingsboardAppConstants {
  static final thingsBoardApiEndpoint = '....'; <- This field
 }

```

and then recompile the app.

However, we will consider your feature request in our upcoming releases.
