### ISSUE TITLE
Error in login: ThingsboardError: message: [Unsupported ThingsBoard platform version: 3.6.0], errorCode: 2, status: null

### ISSUE THREAD

**Issue by 22chandan** [thingsboard/dart_thingsboard_client#38]
Future<void> login() async {
    try {
      tbClient = ThingsboardClient(thingsBoardApiEndpoint.value);
      await tbClient
          .login(LoginRequest('xxxx', 'xxxx'));
      log("isAuthenticated=${tbClient.isAuthenticated()}");
    } catch (e) {
      log('Error in login: $e');
    }
  }

**Comment by ybeshkarov** [comment]
It's not an issue, the minimal supported version is 3.6.3
<img width="1728" alt="Screenshot 2024-07-29 at 14 40 20" src="https://github.com/user-attachments/assets/0d8bae3d-6b05-498d-9931-7cf95bfa71b8">

**Comment by 22chandan** [comment]
what is solution of this so that it donot appear and can fetch smoothly??? @ybeshkarov

**Comment by ybeshkarov** [comment]
You have a few options to consider:

1. **Update your ThingsBoard to version 3.6.3.**
2. **Modify the provided code to bypass this check.** Please note, however, that this approach might require you to resolve additional issues that could arise as a result.

@22chandan

**Comment by DayDreamer-commits** [comment]
@22chandan [this](https://github.com/thingsboard/flutter_thingsboard_app/issues/34#issuecomment-1369974382) might help.
