### ISSUE TITLE
Platform Version Error

### ISSUE THREAD

**Issue by harshadaVM** [thingsboard/dart_thingsboard_client#44]
Hello,

We are using flutter plugin  thingsboard_client: ^1.3.1 in our app.
We are trying to send LoginRequest 
Code block: 
 ThingsboardClient tbClient = ThingsboardClient(thingsBoardApiEndpoint);
    LoginRequest request=LoginRequest(username, password);
    print("Request: ${request.toString()}");
    tbClient.login(request);

but get error as:
Error: DartError: ThingsboardError: message: [Unsupported ThingsBoard platform version: 3.7.0PE], errorCode: 2, status: null
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
packages/thingsboard_client/src/thingsboard_client_base.dart 179:7           _checkPlatformVersion
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 163:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 861:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 890:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 666:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 736:7                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn> 

Thingsboard PE version: 3.7.0PE

As per repository change logs it should work with this version.
Help me with this problem.

**Comment by ybeshkarov** [comment]
Hello,

The minimal supported ThingsBoard version is 3.8.0. That's why you see this message.

**Comment by harshadaVM** [comment]
As per documentation, 1.2.0 supports 3.7.0 
![image](https://github.com/user-attachments/assets/97e9a6e9-7dee-492f-aa0d-870c2e05cbe9)

**Comment by ybeshkarov** [comment]
Correct. 1.2.0 supports 3.6.3+, but I see from your message
> We are using flutter plugin thingsboard_client: ^1.3.1 in our app.

Starting from 1.3.0 the minimal supported ThingsBoard  version is 3.8.0.

**Comment by harshadaVM** [comment]
Okay.
Now I used 1.2.0 but it still gives the same error.

Is there any way to print the pkg version on the console?

**Comment by harshadaVM** [comment]
It works only for 1.2.0.
Thanks.
